#!/bin/bash 

#SBATCH --job-name d2q9-bgk
#SBATCH --nodes 1
#SBATCH --ntasks-per-node 14
#SBATCH --time 00:15:00
#SBATCH --partition cpu

mpirun -l ./d2q9-bgk input_128x128.params obstacles_128x128.dat
