#!/bin/bash 

#SBATCH --job-name d2q9-bgk
#SBATCH --nodes 1
#SBATCH --ntasks-per-node 1
#SBATCH --time 02:00:00
#SBATCH --partition cpu

mpirun -l ./d2q9-bgk input_128x128.params obstacles_128x128.dat > d2q9.1.128x128.out
mpirun -l ./d2q9-bgk input_128x256.params obstacles_128x256.dat > d2q9.1.128x256.out
mpirun -l ./d2q9-bgk input_256x256.params obstacles_256x256.dat > d2q9.1.256x256.out
mpirun -l ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat > d2q9.1.1024x1024.out
